version: "3.8"

services:
  postgres:
    image: postgres
    volumes:
      - $HOME/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=cityevents
    ports:
      - 5432:5432
    container_name: postgres
    networks:
      - cityevents

  postgres-test:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    ports:
      - 5431:5432
    container_name: postgres-test
    networks:
      - cityevents

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: api:v1
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: api
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        npm i
        npm run migrate
        npm run dev
    networks:
      - cityevents
  api-test:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: api-test:v1
    ports:
      - 3001:3000
    volumes:
      - ./:/app
    container_name: test-api
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        npm i
        npm run migrate:undo:all
        npm run migrate
        npm run test
    networks:
      - cityevents

networks:
  cityevents:
