version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=cityevents
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: postgresql
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    container_name: api
    command: sh -c "npx sequelize-cli db:migrate --options-path=src/database/options.ts && npm run dev"

volumes:
  db-data:
